Epsilon/Controllers/ConfiguracionController.cs
using Epsilon.Attributes;
using Epsilon.Models;
using Epsilon.Models.Comun;
using Epsilon.Renders;
using Epsilon.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Negocio.Persistencia;
using Negocio.Persistencia.Modelos;
using Negocio.Servicios;
using Negocio.Servicios.Comun;
using Microsoft.EntityFrameworkCore;
using Calipso.Security;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using AspNetCoreGeneratedDocument;

namespace Epsilon.Controllers
{
    public class ConfiguracionController : AbstractSecurityController
    {
        private readonly IRazorRenderService _renderService;
        private IConfiguracion _configuracion;

        /// <summary>
        /// Constructor d
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="seguridad"></param>
        /// <param name="gestionUsuarios"></param>
        public ConfiguracionController(ILogger<ConfiguracionController> logger, ISeguridad seguridad, IConfiguracion configuracion, IRazorRenderService renderService) : base(logger, seguridad)
        {
            _configuracion = configuracion;
            _renderService = renderService;
        }

        /// <summary> Abre ventana modal para la configuracion del correo </summary>
        [HttpGet, AjaxOnly]
        public async Task<JsonResult> ModalConfigurarCorreo()
        {
            JsonResponse? jsonResponse = new JsonResponse("400", "Error en el servidor", "");
            EpsilonDbContext context = _configuracion.Context;
            ViewFormCorreoElectronico vmConfiguracionCorreo = new ViewFormCorreoElectronico();
            vmConfiguracionCorreo.ModelosCorreo = new SelectList(context.CorreoElectronico.ToList(), nameof(CorreosElectronicos.IdCorreo), nameof(CorreosElectronicos.NombreCorreo));
            string data = await _renderService.ToStringAsync("FormConfigurarCorreo", vmConfiguracionCorreo);
            jsonResponse = new JsonResponse("200", "Operación realizada correctamente.", data);
            return new JsonResult(jsonResponse);
        }

        /// <summary>
        /// Obtiene los datos del modelo seleccionado
        /// </summary>
        /// <param name="idCorreo"></param>
        /// <returns></returns>
        [HttpGet, AjaxOnly]
        public async Task<JsonResult> GetCorreoInfo(int idCorreo)
        {
            JsonResponse? jsonResponse = new JsonResponse("400", "Error en el servidor", "");

            var context = _configuracion.Context;
                     var correo = context.CorreoElectronico
                         .Where(c => c.IdCorreo == idCorreo)
                         .Select(c => new { c.IdCorreo, c.Asunto, c.CuerpoMensaje, c.NombreCorreo })
                         .FirstOrDefault();

            jsonResponse.Data = JsonSerializer.Serialize(correo);
            return new JsonResult(jsonResponse); 
        }

        /// <summary> Guarda los datos introducidos en configuracion modelo correo </summary>
        [HttpPost, AjaxOnly]
        public async Task<JsonResult> AceptarConfiguracionCorreo(CorreoElectronicoViewModel vmModeloCorreo)
        {
            JsonResponse? jsonResponse = new JsonResponse("400", "Error en el servidor", "");
            EpsilonDbContext context = _configuracion.Context;
            CorreosElectronicos correoElectronico = new CorreosElectronicos();

            if (vmModeloCorreo.IdCorreo == 0)
            {
                correoElectronico.NombreCorreo = vmModeloCorreo.NombreCorreoNuevo;
                correoElectronico.Asunto = vmModeloCorreo.Asunto;
                correoElectronico.CuerpoMensaje = vmModeloCorreo.CuerpoMensaje;
                _configuracion.GuardarCorreoNuevo(correoElectronico);
            }
            // Actualizacion
            else
            {
                correoElectronico.IdCorreo = vmModeloCorreo.IdCorreo;
                var modeloSeleccionado = context.CorreoElectronico
                    .Where(c => c.IdCorreo == vmModeloCorreo.IdCorreo)
                    .Select(c => c.NombreCorreo)
                    .FirstOrDefault();
                correoElectronico.NombreCorreo = modeloSeleccionado;
                correoElectronico.Asunto = vmModeloCorreo.Asunto;
                correoElectronico.CuerpoMensaje = vmModeloCorreo.CuerpoMensaje;
                _configuracion.ActualizarDatosCorreo(correoElectronico);
            }

            jsonResponse.Data = JsonSerializer.Serialize(correoElectronico);
            return new JsonResult(jsonResponse);

        }

        /// <summary>
        /// Elimina un Modelo de correo
        /// </summary>
        /// <param name="idCorreo"></param>
        /// <returns></returns>
        [HttpPost, AjaxOnly]
        public async Task<JsonResult> EliminarModeloCorreo(int idCorreo)
        {
            JsonResponse response = new JsonResponse("200", "Ok");

            _configuracion.EliminarModeloCorreo(idCorreo);

            response.StatusMessage = "Se ha eliminado el modelo de correo";
            response.Data = "Usuario eliminado correctamente";
            return new JsonResult(response);
        }

        /// <summary>
        /// Metodo de acceso a la pantalla
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

    }
}

Epsilon/Views/Configuracion/FormConfigurarCorreo.cshtml
@using Epsilon.ViewModels
@model ViewFormCorreoElectronico

<form id="idConfiguracionCorreo_Form" method="post" asp-action="AceptarConfiguracionCorreo" asp-controller="Configuracion">

    <input type="hidden" asp-for="IdCorreo" id="IdCorreo" value="@Model.IdCorreo" />

    <div id="bordeModal">

        @* Modelo de correo *@
        <div class="row">
            <div class="col-md-2">
                <label for="lblModeloCorreo" class="form-label">Modelo Correo</label>
            </div>

            @* Selector del modelo del correo *@
            <div class="col-md-8">
                <select name="ModeloCorreo" class="form-control form-select" asp-items="Model.ModelosCorreo" title="Listado Modelos de Correo" id="ModeloCorreo" style="margin-bottom:5px;">
                    <option value="" selected disabled>-- Seleccione un modelo --</option>
                </select>
            </div>

            @* Boton Mostrar / Ocultar Nombre del correo *@
            <div class="col-md-2">
                <button type="button" id="botonMostrarNombreCorreo" class="btn btn-sm btn-outline-primary" style="font-size:1em;width:30px;height:30px;margin-top:2px;margin-left:-0.5px;" aria-hidden="true">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </button>


                <button type="button" id="botonEliminarCorreo" class="btn btn-sm btn-outline-danger" onclick="return jqPostEliminarModeloCorreo();" style="font-size:1em;width:30px;height:30px;margin-top:2px;margin-left:-0.5px;display: none;" aria-hidden="true" @* disabled *@>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </button>

            </div>
        </div>

        @* Nombre *@
        <div class="row mb-2">
            <div class="col-md-2">
                <label for="lblNombre" id="lblCorreo" class="form-label" style="display:none;">Nombre</label>
            </div>
            <div class="col-md-10">
                <input type="text" class="form-control" id="NombreCorreoNuevo" name="NombreCorreoNuevo" placeholder="Nombre del nuevo modelo de correo" style="display:none;" value="@Model.NombreNuevoCorreo" />
            </div>

        </div>

        @* Asunto *@
        <div class="row mb-2">
            <div class="col-md-2">
                <label for="subject" class="form-label">Asunto:</label>
            </div>
            <div class="col-md-10">
                <input type="text" class="form-control" id="asunto" name="asunto" placeholder="Asunto del mensaje" value="@Model.Asunto">
            </div>
        </div>

        @* Mensaje *@
        <div class="row mb-2">
            <div class="col-md-2">
                <label for="body" class="form-label">Mensaje:</label>
            </div>
            <div class="col-md-10">
                <textarea class="form-control" id="cuerpoMensaje" name="cuerpoMensaje" rows="6" placeholder="Escribe tu mensaje aquí...">@Model.CuerpoMensaje</textarea>
            </div>
        </div>
    </div>

    <div class="mt-2">
        <button id="btnEnviarCorreo" type="submit" class="btn btn-primary ml-1">Aceptar</button>
        <button id="btnCancelar" type="button" class="btn btn-danger ml-1" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
    </div>

</form>

<script>

    document.getElementById("botonMostrarNombreCorreo").addEventListener("click", function () {
        const label = document.getElementById("lblCorreo");
        const input = document.getElementById("NombreCorreoNuevo");
        const icono = this.querySelector("i");
        const selector = document.getElementById("ModeloCorreo");

        // Verifica si los campos están visibles
        const visibles = label.style.display === "block";

        if (visibles) {
            // Ocultar campos
            label.style.display = "none";
            input.style.display = "none";
            // Cambiar ícono a "+"
            icono.classList.remove("fa-minus");
            icono.classList.add("fa-plus");
            selector.disabled = false;
        } else {
            // Mostrar campos
            label.style.display = "block";
            input.style.display = "block";
            input.focus(); // Pone el cursor en el input
            // Cambiar ícono a "−"
            icono.classList.remove("fa-plus");
            icono.classList.add("fa-minus");
            selector.disabled = true;
        }
    });

</script>

Epsilon/Views/Configuracion/Index.cshtml
@model CorreoElectronicoViewModel

@{
    ViewData["Title"] = "Configuracion";
}
@{
    // await Html.RenderPartialAsync("_MensajeOperaciones");
}

<hr>
<h4 class="text-center">
    <i class="fa fa-cogs" aria-hidden="true"></i> Configuracion <i class="fa fa-cogs" aria-hidden="true"></i>
</h4>
<hr>

<button id="AddEdicion" style="padding:5px !important;" type="button" class="btn btn-sm btn-outline-primary pull-right" onclick="return jqGetModalCorreoElectronico()"><span class="fa fa-plus"></span> Correo Electronico</button>

@section Modals {
    @* Modal agregar usuario *@
    <div class="modal fade" tabindex="-1" role="dialog" data-bs-backdrop="static" data-keyboard="false" id="correoModal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-center">
                        <i class="fa fa-user-plus" aria-hidden="true"></i> Configuracion Correo
                    </h5>
                    <button type="button" class="btn-close position-absolute top-0 end-0 m-3" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Aquí se insertará el contenido dinámico -->
                </div>
            </div>
        </div>
    </div>

}

@section Scripts {
    <script src="~/js/Configuracion.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

@section Styles {
    <link href="~/css/Configuracion.css" rel="stylesheet" />
}