Epsilon/Controllers/AgendaController.cs
using Calipso.Security;
using Epsilon.Renders;
using Microsoft.AspNetCore.Mvc;
using Negocio.Servicios;

namespace Epsilon.Controllers
{
    public class AgendaController : AbstractSecurityController
    {
        private readonly IRazorRenderService _renderService;
        private IGestionUsuarios _gestionUsuarios;

        /// <summary>
        /// Constructor d
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="seguridad"></param>
        /// <param name="gestionUsuarios"></param>
        public AgendaController(ILogger<AgendaController> logger, ISeguridad seguridad, IGestionUsuarios gestionUsuarios, IRazorRenderService renderService) : base(logger, seguridad)
        {
            _gestionUsuarios = gestionUsuarios;
            _renderService = renderService;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Epsilon/Controllers/CitasController.cs
using Calipso.Security;
using Epsilon.Renders;
using Microsoft.AspNetCore.Mvc;
using Negocio.Servicios;

namespace Epsilon.Controllers
{
    public class CitasController : AbstractSecurityController
    {
        private readonly IRazorRenderService _renderService;
        private IGestionUsuarios _gestionUsuarios;

        /// <summary>
        /// Constructor d
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="seguridad"></param>
        /// <param name="gestionUsuarios"></param>
        public CitasController(ILogger<CitasController> logger, ISeguridad seguridad, IGestionUsuarios gestionUsuarios, IRazorRenderService renderService) : base(logger, seguridad)
        {
            _gestionUsuarios = gestionUsuarios;
            _renderService = renderService;
        }


        /// <summary>
        /// Handles requests for the default page of the controller.
        /// </summary>
        /// <returns>A view that renders the default page.</returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

Epsilon/Controllers/ClinicasController.cs
using Calipso.Security;
using Epsilon.Renders;
using Microsoft.AspNetCore.Mvc;
using Negocio.Servicios;

namespace Epsilon.Controllers
{
    public class ClinicasController : AbstractSecurityController
    {
        private readonly IRazorRenderService _renderService;
        private IGestionUsuarios _gestionUsuarios;

        /// <summary>
        /// Constructor d
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="seguridad"></param>
        /// <param name="gestionUsuarios"></param>
        public ClinicasController(ILogger<ClinicasController> logger, ISeguridad seguridad, IGestionUsuarios gestionUsuarios, IRazorRenderService renderService) : base(logger, seguridad)
        {
            _gestionUsuarios = gestionUsuarios;
            _renderService = renderService;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Epsilon/Controllers/MedicosController.cs
using Calipso.Security;
using Epsilon.Renders;
using Microsoft.AspNetCore.Mvc;
using Negocio.Servicios;

namespace Epsilon.Controllers
{
    public class MedicosController : AbstractSecurityController
    {
        private IRazorRenderService _renderService;
        private IGestionUsuarios _gestionUsuarios;

        /// <summary>
        /// Constructor d
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="seguridad"></param>
        /// <param name="gestionUsuarios"></param>
        public MedicosController(ILogger<MedicosController> logger, ISeguridad seguridad, IGestionUsuarios gestionUsuarios, IRazorRenderService renderService) : base(logger, seguridad)
        {
            _gestionUsuarios = gestionUsuarios;
            _renderService = renderService;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Epsilon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <!-- Icono de la pestaña de la pagina -->
    <link rel="shortcut icon" href="~/media/epsilonIcono.ico">
    
    <!-- Titulo de la pestaña de la pagina -->
    <title>@ViewData["Title"] - Epsilon</title>
    <script type="importmap"></script>
    
    <!-- Referencia a FontAwesome -->
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

    <!-- Referencia a BootStrap -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <!-- Referencia a site.css -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Epsilon.styles.css" asp-append-version="true" />


    <!-- Enlaces a los archivos .css y .js del panel fijo lateral derecho -->
@* 
 <script src="~/js/switch/theamswitcher.js"></script>
    <link href="~/js/switch/themeswitch.css" rel="stylesheet" /> *@

    @RenderSection("Styles", required: false)
    @RenderSection("Modals", required: false)
</head>
<body>


@*     <div id="background-grid"></div>

 *@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-color:grey !important;border-bottom-color:yellow !important">

            <div class="container-fluid" style="background-color:grey">

                @* IMAGEN APP *@
                <a class="navbar-brand" asp-controller="home" asp-action="index" style="margin-top:-7px;">
                    <img src="~/media/epsilon.png" width="20" height="20" />
                </a>

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Epsilon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="background-color:gainsboro">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @* (1) HOME - INICIO *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <span class="fa fa-home"></span>  Inicio</a>
                        </li>

                        @* (2) - USUARIOS *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">
                                <span class="fa fa-user"></span>  Usuarios
                            </a>         
                        </li>
                   
                        @* (3) - MEDICOS *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicos" asp-action="Index">
                                <span class="fa-solid fa-user-doctor"></span>  Medicos
                            </a>
                        </li>

                        @* (4) - PACIENTES *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pacientes" asp-action="Index">
                                <span class="fa-solid fa-user-injured"></span>   Pacientes</a>
                        </li>

                        @* (5) - CLINICAS *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clinicas" asp-action="Index">
                                <span class="fa-solid fa-hospital"></span>  Clinicas</a>
                        </li>

                        @* (6) - CITAS *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Citas" asp-action="Index">
                                <span class="fa-solid fa-file-circle-check"></span> Citas</a>
                        </li>

                        @* (7) - AGENDA *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agenda" asp-action="Index">
                                <span class="fa fa-calendar"></span>  Agenda
                            </a>
                        </li>

                        @* (8) - TRATAMIENTOS *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tratamientos" asp-action="Index">
                                <span class="fa-solid fa-file-medical"></span>  Tratamientos
                            </a>
                        </li>

                        @* (8) - RADIOLOGIA *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Radiologia" asp-action="">
                                <span class="fa-solid fa-circle-radiation"></span>  Radiologia
                            </a>
                        </li>

                        @* (9) - FACTURACION *@
                        <li class="nav-item" style="padding:0px 10px 0px 10px;" id="botonMenu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Facturacion" asp-action="Index">
                                <span class="fa-solid fa-sack-dollar"></span>  Facturacion</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

     @*    <div id="secectionBox">

            <div id="themeContainer" style="border:1px solid yellow;">

                <!--Boton para cerrar el panel -->
                <div id="hideme" class="themeTitle" style="cursor: pointer;">CERRAR </div>

                <!-- Seccion (1) : DATOS USUARIO -->
                <div class="themeName" style="margin-bottom:15px;">&#11088; JMD SOFTWARE &#11088;</div>

                <!-- Video -->
                <video style="width:100%;height:99px;background-position: center;" autoplay muted loop>
                    <source src="Videos/Motion.mp4" type="video/mp4" />
                </video>

                <!-- Datos del usuario -->
                <div style="margin-top:-95px; line-height: 1em;">
                    <asp:Label runat="server" ID="lblNombre" Font-Size="9pt"></asp:Label><br />
                    <asp:Label runat="server" ID="lblEmail" Font-Size="9pt"></asp:Label><br />
                    <asp:Label runat="server" ID="lblTelefono" Font-Size="9pt"></asp:Label><br />
                    <asp:Label runat="server" ID="lblFechaAlta" Font-Size="9pt"></asp:Label><br />
                    <asp:Label runat="server" ID="lblRutaFoto" Font-Size="9pt"></asp:Label>
                    <br />
                </div>

                <br />

                <!-- Seccion (2) : MENU OPCIONES -->
                <div class="themeName" style="margin-bottom:10px;">&#128295; AJUSTES &#128295;</div>

                <!-- Opciones Panel Lateral -->
                <ul style="text-align:left;margin-left:5px;font-size:9pt;list-style-type: square;color:yellow;">
                    <li><a href="AjustesUsuario.aspx">Mi Perfil</a></li>
                    <li><a href="Usuarios.aspx">Usuarios</a></li>
                    <li><a href="Pruebas.aspx">Pruebas JS</a></li>
                    <li><a href="PruebasjQuery.aspx">Pruebas jQuery</a></li>
                    <li><a href="Bootstrap.aspx">Bootstrap</a></li>
                    <!--<li><a href="EmojiIcons.aspx">Emojis</a></li>-->
                    <li><a href="ControlesEspeciales.aspx">Controles Especiales</a></li>
                    <li><a href="Login.aspx" onclick="CerrarSesion">Cerrar Sesion</a></li>
                </ul>

                <!-- Seccion (3) : PERSONALIZACION -->
                <div class="themeName">PERSONALIZACION</div>

                <p style="font-size: 9pt; font-family: arial; color: grey;">
                    Selecciona desde aquí el color de esta web a tu gusto.
                </p>

                <!-- Desplegable de seleccion del color -->
                <select onchange="changeTheme()" id="option" style="border-radius: 5px; margin-bottom: 10px; width: 80%; background-color: teal;">
                    <option>WHITE</option>
                    <option selected="selected">GREY</option>
                    <option>ORANGE</option>
                    <option>SKYBLUE</option>
                    <option>YELLOW</option>
                    <option>RED</option>
                    <option>GOLD</option>
                    <option>PINK</option>
                    <option>GREEN</option>
                </select>

                <br />
                <br />

            </div>
            <!--Fin 'secectionBox'-->
        </div> *@


        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-center" style="border-top:1px solid black;background-color:grey;border-top-color:yellow !important">
        <div class="container" style="text-align: center; margin-top: 5px; text-shadow: 2px 2px 3px rgba(0, 0, 0, 0.3);">
         
            <img src="~/media/JMDnegro.png" alt="" height="25px" width="50px" /> © Copyright 2025 The JSM Company, all rights reserved. JSM<sup>® </sup>and JMD Logo<sup>® </sup>
                are trademarks of The JMD Corporation. All rights Reserved.
            <img src="~/media/JMDnegro.png" alt="" height="25px" width="50px" />               
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>


<style>
 /*     .nav-item:hover {
 background-color:grey;
     } */
    #botonMenu:hover{
       background-color:yellow
    }




</style>

Epsilon/Views/Shared/_MensajesOperaciones.cshtml
@* <div id="idDivMsg" class="bd-callout bd-calllout-info visually-hidden" onclick="$('#idDivMsg').addClass('visually-hidden')">
    <h4 id="specific-markup-required-for-dismiss-on-next-click">Operaciones de @ViewData["Title"]</h4>
        <p id="idMsg"></p>
</div>



<div id="idDivMsgError" class="bd-callout bd-calllout-danger visually-hidden" onclick="$('#idDivMsgError').addClass('visually-hidden')">
    <h4 id="specific-markup-required-for-dismiss-on-next-click">Operaciones de @ViewData["Title"]</h4>
    <p id="idMsgError"></p>
</div>

 *@


<div id="idDivMsg" class="alert alert-info visually-hidden" role="alert">
    <div class="row">

        <div class="col-md-10">
            <h4 class="alert-heading">Operaciones de @ViewData["Title"]</h4>
        </div>
        <div class="col-md-2">
            <p id="idMsg"></p>
        </div>

        <i class="fa fa-exclamation-triangle fa fa-pull-right" aria-hidden="true"></i>
    </div>

</div>


<div id="idDivMsgError" class="alert alert-danger visually-hidden" role="alert">
    <div class="col-md-10">
        <h4 class="alert-heading">Operaciones de @ViewData["Title"]</h4>
        <p id="idMsgError"></p>
    </div>
@*     <div class="col-md-2">
        <i class="fa fa-exclamation-triangle fa fa-pull-right" style="font-size:5rem !important;float:right;" aria-hidden="true"></i>
    </div> *@

</div>

Epsilon/Views/Shared/_TituloPagina.cshtml
<hr style="color:white;">
<button id="volverInicio" type="button" class="btn btn-sm btn-outline-light fa-pull-left" title="Volver a Inicio" onclick="window.location.href='@Url.Action("Index", "Home")';" style="font-size:1.5em;width:40px;height:40px;"><span class="fa fa-home"></span></button>
<button id="ayuda" type="button"
        class="btn btn-sm btn-outline-light fa-pull-right"
        style="font-size:1.5em;width:40px;height:40px;"
        title="Ayuda"
        onclick="abrirWord()">
    <span class="fa fa-question-circle"></span>
</button>

<script>
    function abrirWord() {
        fetch('/Usuarios/AbrirWord', {
            method: 'POST'
        })
        .then(response => {
            if (response.ok) {
                console.log("Word abierto");
            } else {
                response.text().then(t => alert(t));
            }
        })
        .catch(err => alert("Error al abrir Word: " + err));
    }
</script>
<h4 class="text-center" style="color:white;"><span class="fa fa-user"></span> Usuarios <span class="fa fa-user"></span></h4>


<hr style="color:white;margin-top:27px;">



<div class="text-center">
@*     <h2>
        <a href="#" target="_blank" style="color:black; text-decoration:none; padding-right:60px; ">
            <font size="5">Programa de Gestión de Actividades de Formación</font>
        </a>
    </h2> *@



@*     <h3>@ViewData["Title"]</h3> *@
</div>